### ISSUE TITLE
Using markdown-it plugin breaks the subcomponents inside the markdown file in nuxt

### ISSUE THREAD

**Issue by carluri** [hmsk/frontmatter-markdown-loader#142] opened 2020-04-19 19:58 UTC
I'm having an issue rendering vue components within the markdown files when trying to use the `highlightjs` or `prism` to highlight code. I'm using Nuxt.

When my configuration is:
```
{
  test: /\.md$/,
  loader: 'frontmatter-markdown-loader',
  options: {
          mode: [Mode.VUE_COMPONENT]
  }
```
The components inside the markdown are rendered correctly, but then my code is not highlighted.

When I change the configuration to look like this:

```
{
  test: /\.md$/,
  loader: 'frontmatter-markdown-loader',
  options: {
          mode: [Mode.VUE_COMPONENT],
          markdownIt:{
            html: true
          }          
  }
```
Everything works ok too, which is expected as this is the default configuration.

However, if I try to use a markdownIt renderer or to extend for use with a highlighting plugin everything breaks.

```
const markdownIt = require('markdown-it');
const markdownItPrism = require('markdown-it-prism');

{
  test: /\.md$/,
  loader: 'frontmatter-markdown-loader',
  options: {
          mode: [Mode.VUE_COMPONENT],
          markdownIt: markdownIt({ html: true })
  }
```
or with the plugin

```
const markdownIt = require('markdown-it');
const markdownItPrism = require('markdown-it-prism');

{
  test: /\.md$/,
  loader: 'frontmatter-markdown-loader',
  options: {
          mode: [Mode.VUE_COMPONENT],
          markdownIt: markdownIt({ html: true }).use(markdownItPrism)
  }
```

The html (although `html:true` is there) is just rendered as normal text and the code is not highlighted either.

Am I missing something or is just that this functionality is not there? If the latter, is there any suggested workaround?

At this point I'm stuck either being able to highlight code if the `Mode` is `Mode.html` but this doesn't render the components within the markdown, or to render the components with `Mode.VUE_COMPONENT` but then the code is not highlighted. 

Any help with this is appreciated. Thank you.

**Comment by hmsk** [comment] 2020-04-19 20:55
I just confirmed `markdownIt({ html: true }).use(markdownItPrism)` works correctly in the sample repo.
https://github.com/hmsk/frontmatter-markdown-loader-nuxt-sample/pull/2

I guess you missed to provide a stylesheet which `markdown-it-prism` requires.

> The plugin will insert the necessary markup into all code blocks. Include one of Prism’s stylesheets in your HTML to get highlighted code.

https://github.com/jGleitz/markdown-it-prism

In Nuxt, adding `prismjs/themes/prism.css` (this referrs `node_modules/prismjs/...`) in `css` block on `nuxt.config.(ts|js)` is the quickest way.

https://github.com/hmsk/frontmatter-markdown-loader-nuxt-sample/blob/2ce32c91dcadc9c65786369965c3942817451c8a/nuxt.config.js#L17-L20

**Comment by carluri** [comment] 2020-04-20 03:57
Thanks for looking into this @hmsk . I did have the stylesheet required by `markdown-it-prism`. I checked your code and it still didn't work.

However, I was able to solve it doing the following:

``` javascript
var md = require("markdown-it")({html:true}).use(require("markdown-it-prism"));

css: [
    'prismjs/themes/prism-vsc-dark-plus.css',
  ],

build: {
    extend(config, ctx) {
      config.module.rules.push({
        test: /\.md$/,
        include: [
          path.resolve(__dirname, "content"),
        ],
        loader: "frontmatter-markdown-loader",
        options: {
          mode: [Mode.VUE_COMPONENT],
          markdown: body => {
            return md.render(body);
          }
        }
      });
  }

```

So for some reason that is not clear to me it did not work using the `markdownIt` options when extending the webpack config. But it worked when  using the `markdown` option. This is however not the way is shown in the documentation. Maybe you can clarify?

Thank you

**Comment by hmsk** [comment] 2020-04-20 04:51
As we can see the actual working example https://github.com/hmsk/frontmatter-markdown-loader-nuxt-sample/pull/2#issuecomment-616222958 on our browser, I think it's just your local's trouble.

Happy to look into more if you provide a reproducible repository 😉

**Comment by hmsk** [comment] 2020-04-27 08:09
Closing this issue since we don't have any discussion over a week. I welcome to reopen when a reproducible repository is provided.

**Closed by hmsk** 2020-04-27 08:09 UTC

**Comment by hmsk** [comment] 2020-06-16 11:37
I found the missing piece between us. I found the object by `require('markdown-it')` doesn't work for `markdownIt` option. However, my codes in sample repo were using `import MarkdownIt from 'markdown-it'`. The root problem is fixed in https://github.com/hmsk/frontmatter-markdown-loader/releases/tag/v3.6.0 😉

**Comment by carluri** [comment] 2020-07-06 17:03
Thanks for looking into this @hmsk (and apologies for the late reply have been busy with other things). I will take a look at the changes this week and will let you know if I still run into some issues. This looks very promising though, thanks again.
